# Generated by Django 5.2.8 on 2025-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_bloodrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
